// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace HWIZ.Data.Models;

public partial class Ferias
{
    [Key]
    public int id { get; set; }

    public int? idUtilizador { get; set; }

    [Column(TypeName = "date")]
    public DateTime? dataInicio { get; set; }

    [Column(TypeName = "date")]
    public DateTime? dataFim { get; set; }

    [Column(TypeName = "date")]
    public DateTime? createdAt { get; set; }

    [Column(TypeName = "date")]
    public DateTime? updatedAt { get; set; }
}