// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace HWIZ.Data.Models;

public partial class HWIZAPPContext : DbContext
{
    public HWIZAPPContext(DbContextOptions<HWIZAPPContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Ferias> Ferias { get; set; }

    public virtual DbSet<Utilizadores> Utilizadores { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Utilizadores>(entity =>
        {
            entity.Property(e => e.createdAt).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}